# Generated by Django 5.1.3 on 2024-11-13 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.IntegerField(blank=True, choices=[(1, 'Mobile Phones'), (2, 'Smartphones'), (3, 'Laptops'), (4, 'TVs'), (5, "Men's Clothing"), (6, "Women's Clothing")], null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.IntegerField(choices=[(1, 'Electronics'), (2, 'Clothing')]),
        ),
    ]
